### ISSUE TITLE
JasperReports as Tomcat default application in URL

### ISSUE THREAD

**Issue by Dreamerset** [bitnami/bitnami-docker-jasperreports#109]
Standard deployment of jasperreports  (docker pull bitnami/jasperreports - under Ubuntu 20.04.3 LTS)  

```
version: '3.7'
services:
  jasperServerDB:
    container_name: jasperServerDB
    image: docker.io/bitnami/mariadb:latest
    ports:
      - '3306:3306'
    volumes:
      - './jasperServerDB_data:/bitnami/mariadb'
    environment:
      - MARIADB_ROOT_USER=mariaDbUser
      - MARIADB_ROOT_PASSWORD=mariaDbPassword
      - MARIADB_DATABASE=jasperServerDB
  jasperServer:
    container_name: jasperServer
    image: docker.io/bitnami/jasperreports:latest
    ports:
      - '8085:8080'
    volumes:
      - './jasperServer_data:/bitnami/jasperreports'
    depends_on:
      - jasperServerDB
    environment:
      - JASPERREPORTS_DATABASE_HOST=jasperServerDB
      - JASPERREPORTS_DATABASE_PORT_NUMBER=3306
      - JASPERREPORTS_DATABASE_USER=dbUser
      - JASPERREPORTS_DATABASE_PASSWORD=dbPassword
      - JASPERREPORTS_DATABASE_NAME=jasperServerDB
      - JASPERREPORTS_USERNAME=adminUser
      - JASPERREPORTS_PASSWORD=adminPassword
    restart: on-failure
```

The reporting server is behind nginx reverse proxy which points to port 8085 of the docker machine.  

Everything works as expected on https://my.domain.com/jasperserver/ url.  

It is required to have JasperReports server responding on only https://my.domain.com/ url.  
  
![image](https://user-images.githubusercontent.com/17952370/148982307-4155d056-c850-48c4-9ca6-592c7f7469e7.png)

What is the recommended/best approach to configure the container (default Tomcat application) which can survive container's restarts and updates?

Some results from searching the net:  
[https://cwiki.apache.org/confluence/display/tomcat/HowTo#HowTo-HowdoImakemywebapplicationbetheTomcatdefaultapplication?](https://cwiki.apache.org/confluence/display/tomcat/HowTo#HowTo-HowdoImakemywebapplicationbetheTomcatdefaultapplication?) 
https://coderanch.com/t/85615/application-servers/set-application-default-application  
https://benhutchison.wordpress.com/2008/07/30/how-to-configure-tomcat-root-context/  

Which doubtfully are applicable to bitnami containers.  

Hopefully there is a simple image configuration which could be included in the docker-compose.yml file.

[Reference to StackOverflow same question](https://stackoverflow.com/questions/70685619/jasperreports-as-tomcat-default-application-in-url)
