### ISSUE TITLE
Support for existing mysql or mariadb

### ISSUE THREAD

**Issue by cemo** [bitnami/bitnami-docker-jasperreports#40]
Hi, 

I am using cloud my sql services and I would like to use your image with my existing mysql server. Is it possible to configure it? 

Thanks

**Comment by dbarranco** [comment]
Hi @cemo 

If you want to use an existing mysql server you can modify the `docker-compose.yml` in order to connect the server to an existing mysql server.

```
version: '2'

services:
    jasperreports:
      image: bitnami/jasperreports:latest
      ports:
        - '80:8080'
        - '443:8443'
      volumes:
        - jasperreports_data:/bitnami/jasperreports
      environment:
        - MARIADB_USER=example_user
        - MARIADB_PASSWORD=password
        - MARIADB_HOST=server_ip
        - MARIADB_PORT= server_port
volumes:
  jasperreports_data:
    driver: local
```

> Note: Take into account that you have to configure the user/password of mysql with privileges to create databases on your server.

I tested that configuration and it's working fine:
```
jasperreports_1  | nami    INFO  Initializing jasperreports
jasperreports_1  | jasperr INFO  Preparing JasperReports environment...
jasperreports_1  | mysqlCo INFO  Trying to connect to MySQL server
jasperreports_1  | mysqlCo INFO  Found MySQL server listening at 35.187.51.75:3306
jasperreports_1  | mysqlCo INFO  MySQL server listening and working at 35.187.51.75:3306
jasperreports_1  | jasperr INFO  Configuring JasperReports settings...
jasperreports_1  | jasperr INFO  Deploying JasperReports...
```

Best regards!
