### ISSUE TITLE
Feature Request: ENV Variables like JAVA_OPTS

### ISSUE THREAD

**Issue by psanzm** [bitnami/bitnami-docker-jasperreports#42]
Hi, I don't know if there are already a way to set this variables in the jasperserver container, but will be very handy having additional **Environment variables** like the bitnami/tomcat container (https://hub.docker.com/r/bitnami/tomcat/) such _JAVA_OPTS_ or _TOMCAT_ALLOW_REMOTE_MANAGEMENT_.

I tried to raise the java memory setting this options in the setenv.sh file (_/opt/bitnami/tomcat/bin/setenv.sh_) but with no luck :/

Regards and thank you so much for your work in advance.

**Comment by sameersbn** [comment]
Hi @psanzm, did you try specifying `JAVA_OPTS` as an container environment variable?

**Comment by sameersbn** [comment]
I have been investigating this request further. You can customize the java memory settings by defining the container env variable `JAVA_OPTS` or `CATALINA_OPTS`. However, In my tests I found that using double quotes in the variable declaration can cause problems while interpreting these variables.

Please refer to the below `docker-compose.yml` example

```yaml
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  jasperreports:
    image: 'bitnami/jasperreports:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'jasperreports_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - CATALINA_OPTS=-Xms512m -Xmx2048m -XX:PermSize=64m -XX:MaxPermSize=128m
volumes:
  mariadb_data:
    driver: local
  jasperreports_data:
    driver: local
```

You may also find the folling link useful - https://stackoverflow.com/questions/11222365/catalina-opts-vs-java-opts-what-is-the-difference

Do let us know if this helps. 
Best Regards.
