### ISSUE TITLE
Error executing 'postInstallation': EEXIST: file already exists

### ISSUE THREAD

**Issue by qzvt** [bitnami/bitnami-docker-jasperreports#56]
Hi,

I got the error when I run docker compose and I try persistence data then the error says:

```
compose file    
"  - ./jasperreports_persistence:/bitnami"
```
```
Error!
jasperserver     | Error executing 'postInstallation': EEXIST: file already exists, symlink '/opt/bitnami/jasperreports' -> '/opt/bitnami/tomcat/data/jasperserver'
jasperserver exited with code 1
```
Can I fix it?

Thank you.

**Comment by tompizmor** [comment]
Hi @qzvt,

For some reason, the persistent data dir is corrupted. 
I have tried with this docker-compose file from scratch and it worked fine for me:

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=bn_jasperreports
      - MARIADB_DATABASE=bitnami_jasperreports
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  jasperreports:
    image: 'bitnami/jasperreports:7'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - JASPERREPORTS_DATABASE_USER=bn_jasperreports
      - JASPERREPORTS_DATABASE_NAME=bitnami_jasperreports
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - './jasperreports_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
```

I would try to clean the environment and start again from scratch. If you are doing something else rather than just running `docker-compose up` in the same folder where the docker-compose file is, let me know so I can try to reproduce it accordingly.
