### ISSUE TITLE
Mariadb does not start

### ISSUE THREAD

**Issue by boydenus** [bitnami/bitnami-docker-jasperreports#65]
**Issue:** 
MariaDB container does not start. Ran docker container ls and only the jasperreports container shows as running. Attempting to access the host server at http://_hostname_/jasperserver results in page not found error (also tried by IP address). New Ubuntu host on VMware ESXi, followed Bitnami documentation for docker, docker-compose, and jasperreports docker install on Ubuntu 18.04.

**Host O/S and Version:** Ubuntu 18.04.3 LTS
**Docker Version:** 19.03.1
**docker info Output:**
```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 2
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-58-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.696GiB
 Name: boydenus-jasper
 ID: H7OE:LYW2:AMBA:SHPK:ZDKE:XLPQ:GPWY:HNOL:ZBPV:LUR7:SQR5:RFHS
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
**Command to run containers:** 
```
docker-compose up -d (from /home/trboyden where docker-compose.yml file is)
```
**docker-compose.yml contents:**
```yaml
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - MARIADB_USER=bn_jasperreports
      - MARIADB_DATABASE=bitnami_jasperreports
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/home/trboyden/bitnami/mariadb:/bitnami'
  jasperreports:
    image: 'bitnami/jasperreports:7'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - JASPERREPORTS_DATABASE_USER=bn_jasperreports
      - JASPERREPORTS_DATABASE_NAME=bitnami_jasperreports
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - '/home/trboyden/bitnami/jasper:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  jasperreports_data:
    driver: local
```
**docker container ls output:**
```
CONTAINER ID
e20ec5658d0e

IMAGE
bitnami/jasperreports:7

COMMAND
"/app-entrypoint.sh …"

CREATED
About an hour ago

STATUS
Up 2 minutes

PORTS
0.0.0.0:80->8080/tcp, 0.0.0.0:443->8443/tcp

NAMES
trboyden_jasperreports_1
```
