### ISSUE TITLE
Error executing 'postInstallation': ENOTSUP: operation not supported on socket, symlink '/opt/bitnami/jasperreports' -> '/opt/bitnami/tomcat/data/jasperserver'

### ISSUE THREAD

**Issue by vimalraj-a** [bitnami/bitnami-docker-jasperreports#72]
Failed to deploy on AKS with File share volume mount

**Steps to reproduce the issue:**

1. Deploy the jasperreports7.2.0 on AKS
2. VolumeClaim should be file share

**Describe the results you received:**
Error executing 'postInstallation': ENOTSUP: operation not supported on socket, symlink '/opt/bitnami/jasperreports' -> '/opt/bitnami/tomcat/data/jasperserver'

**Describe the results you expected:**
Should start the jasperserver like `docker-compose up -d`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community                            
 Version:           19.03.1                                  
 API version:       1.40                                     
 Go version:        go1.12.5                                 
 Git commit:        74b1e89                                  
 Built:             Thu Jul 25 21:17:08 2019                 
 OS/Arch:           windows/amd64                            
 Experimental:      false                                    
                                                             
Server: Docker Engine - Community                            
 Engine:                                                     
  Version:          19.03.1                                  
  API version:      1.40 (minimum version 1.12)              
  Go version:       go1.12.5                                 
  Git commit:       74b1e89                                  
  Built:            Thu Jul 25 21:17:52 2019                 
  OS/Arch:          linux/amd64                              
  Experimental:     false                                    
 containerd:                                                 
  Version:          v1.2.6                                   
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb 
 runc:                                                       
  Version:          1.0.0-rc8                                
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f 
 docker-init:                                                
  Version:          0.18.0                                   
  GitCommit:        fec3683                                  
```

- Output of `docker info`:

```
Client:                                                                       
 Debug Mode: false                                                            
                                                                              
Server:                                                                       
 Containers: 25                                                               
  Running: 6                                                                  
  Paused: 0                                                                   
  Stopped: 19                                                                 
 Images: 54                                                                   
 Server Version: 19.03.1                                                      
 Storage Driver: overlay2                                                     
  Backing Filesystem: extfs                                                   
  Supports d_type: true                                                       
  Native Overlay Diff: true                                                   
 Logging Driver: json-file                                                    
 Cgroup Driver: cgroupfs                                                      
 Plugins:                                                                     
  Volume: local                                                               
  Network: bridge host ipvlan macvlan null overlay                            
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk
 Swarm: active                                                                
  NodeID: x2zar3ydocjm2nbm5wxjalcrn                                           
  Is Manager: true                                                            
  ClusterID: ltemh40lgr3k2babg234z6ksq                                        
  Managers: 1                                                                 
  Nodes: 1                                                                    
  Default Address Pool: 10.0.0.0/8                                            
  SubnetSize: 24                                                              
  Data Path Port: 4789                                                        
  Orchestration:                                                              
   Task History Retention Limit: 5                                            
  Raft:                                                                       
   Snapshot Interval: 10000                                                   
   Number of Old Snapshots to Retain: 0                                       
   Heartbeat Tick: 1                                                          
   Election Tick: 10                                                          
  Dispatcher:                                                                 
   Heartbeat Period: 5 seconds                                                
  CA Configuration:                                                           
   Expiry Duration: 3 months                                                  
   Force Rotate: 0                                                            
  Autolock Managers: false                                                    
  Root Rotation In Progress: false                                            
  Node Address: 192.168.65.3                                                  
  Manager Addresses:                                                          
   192.168.65.3:2377                                                          
 Runtimes: runc                                                               
 Default Runtime: runc                                                        
 Init Binary: docker-init                                                     
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb                 
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f                       
 init version: fec3683                                                        
 Security Options:                                                            
  seccomp                                                                     
   Profile: default                                                           
 Kernel Version: 4.9.184-linuxkit                                             
 Operating System: Docker Desktop                                             
 OSType: linux                                                                
 Architecture: x86_64                                                         
 CPUs: 2                                                                      
 Total Memory: 1.952GiB                                                       
 Name: docker-desktop                                                         
 ID: M5NC:7LX6:6CLC:GS5K:CI4J:D3XG:LDDO:SEXW:G5OX:TLUR:YKLR:R6UM              
 Docker Root Dir: /var/lib/docker                                             
 Debug Mode: true                                                             
  File Descriptors: 81                                                        
  Goroutines: 207                                                             
  System Time: 2019-10-29T09:14:00.23761Z                                     
  EventsListeners: 3                                                          
 Registry: https://index.docker.io/v1/                                        
 Labels:                                                                      
 Experimental: false                                                          
 Insecure Registries:                                                         
  127.0.0.0/8                                                                 
 Live Restore Enabled: false                                                  
 Product License: Community Engine                                            
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
AWS AKS and Fileshare volume mount

**Comment by juan131** [comment]
Hi @vimalraj-a 

Could you try using the **deployment.yaml** below?

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jasperreports
  labels:
    app: jasperreports
spec:
  selector:
    matchLabels:
      app: jasperreports
  template:
    metadata:
      labels:
        app: jasperreports
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: jasperreports
          image: bitnami/jasperreports:7.2.0-debian-9-r135
          imagePullPolicy: "IfNotPresent"
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: MARIADB_HOST
              value: azure-mariadb-dev-svc
            - name: MARIADB_PORT_NUMBER
              value: "3505"
            - name: JASPERREPORTS_DATABASE_NAME
              value: "bitnami_jasperreports"
            - name: JASPERREPORTS_DATABASE_USER
              value: "bn_jasperreports"
            - name: JASPERREPORTS_USERNAME
              value: "user"
          ports:
            - name: web
              containerPort: 8080
          volumeMounts:
            - name: jasperreports-data
              mountPath: /bitnami/jasperreports
      volumes:
        - name: jasperreports-data
          persistentVolumeClaim:
            claimName: jasper-datadevfilepvc
```

It's almost the same manifest but modifying the **mountPath** for the data PV.
