### ISSUE TITLE
lost data after running docker compose down 

### ISSUE THREAD

**Issue by shyamjos** [bitnami/bitnami-docker-jasperreports#76]
**Description**

We lost our jasper server data after running the command `docker compose down` , by default `docker compose down` do not remove persistent volume associated with container but in our case we lost the data when started it again with command `docker compose up -d` , is this normal behaviour ?

**Steps to reproduce the issue:**

1. `docker compose down`
2. `docker compose up`

**Describe the results you received:**

Lost all data (reports and user accounts )

**Describe the results you expected:**

no data loss!! 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Docker version 19.03.1, build 74b1e89

```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 22
  Running: 22
  Paused: 0
  Stopped: 0
 Images: 222
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: fluentd
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-1058-aws
 Operating System: Ubuntu 18.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.806GiB
 Name: web-chat-dev
 ID: T545:HS55:M5N7:IRYJ:WVI4:HX6Q:YR2P:QXBJ:QN47:NRAE:Q5CM:KP7R
 Docker Root Dir: /docker-data/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

compose file 

version: '2'
services:
  mariadb:
    restart: always
    image: 'bitnami/mariadb:10.3'
    environment:
      - MARIADB_USER=bn_jasperreports
      - MARIADB_DATABASE=bitnami_jasperreports
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  jasperreports:
    restart: always
    image: 'bitnami/jasperreports:6.3.0-r11'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - JASPERREPORTS_DATABASE_USER=bn_jasperreports
      - JASPERREPORTS_DATABASE_NAME=bitnami_jasperreports
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '3371:8080'
      - '3372:8443'
    volumes:
      - 'jasper_data:/bitnami'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  jasper_data:
    driver: local

**Comment by shyamjos** [comment]
I have ebs snapshot of docker volume , is there a way to recover data by copying jasper volume data from this ebs snapshot ?

**Comment by dani8art** [comment]
Hi @shyamjos 

Thank you for reporting this issue. I've tried to reproduce the issue but I couldn't. I followed the steps but the issue didn't happen.

```bash
docker-compose down
docker-compose up -d
```
could you check if the volumes are there? please, execute `docker volume ls`.

> I have ebs snapshot of docker volume, is there a way to recover data by copying jasper volume data from this ebs snapshot ?

I would say that if in the snapshot the volume existed and you apply the snapshot it should return. Then when you execute the `docker-compose up -d` it should be found. 

Regards.

**Comment by shyamjos** [comment]
yes, volumes are there!
```
DRIVER              VOLUME NAME
local               jasper-reports_jasperreports_data
local               jasper-reports_mariadb_data
```
I lost all data when i tried `docker-compose down`  (lost all users & reports created)
steps to reproduce

```
docker-compose down

Stopping jasper-reports_jasperreports_1 ... done
Stopping jasper-reports_mariadb_1       ... done
Removing jasper-reports_jasperreports_1 ... done
Removing jasper-reports_mariadb_1       ... done
Removing network jasper-reports_default

docker-compose up -d

Creating network "jasper-reports_default" with the default driver
Creating jasper-reports_mariadb_1 ... done
Creating jasper-reports_jasperreports_1 ... done

```

**Comment by dani8art** [comment]
Hi, I realized that I was using the latest version of the image. Yes, you are right if I use `6.3.0-r11` the database is not restored, we had that issue in this version of the image. 

Fortunately, you can execute a workaround and you can restore your data because the data is still there in the database image, so you can try the following:

1. Search into MariaDB your database, execute:
```
docker-compose exec jasperreports \
  mysql \
  -hmariadb \
  -e "select distinct table_schema from information_schema.tables \
        where table_type = 'BASE TABLE' \
        and table_schema not in ('information_schema','mysql','performance_schema','sys') \
        order by table_schema;"
```
It is going to show you several databases all of them with the same pattern `bitnami_jasperreports_XXXX` where XXXX is a random suffix. For each of them execute the following command in order to find the one that contains your data.

```
docker-compose exec jasperreports \
  mysql \
  -hmariadb \
  -e "select * from bitnami_jasperreports_<changeme>.JIUser;"
```

2. There should be one database that shows your data, get the name, `bitnami_jasperreports_XXXX`, and create a backup of your data.

```
docker-compose exec mariadb mysqldump -u root bitnami_jasperreports_XXXX > backup.sql
```

3. Once you have your `backup.sql` then update the jasperreports image to the latest version of the branch 6. `6.4.3-r30` and change the name of the volumes in order to recreate them.
```
docker-compose down
```

```diff
  mariadb:
    volumes:
-      - 'mariadb_data:/bitnami'
+      - 'mariadb_data_v2:/bitnami'
  jasperreports:
+    image: 'bitnami/jasperreports:6.4.3-r30'
-    image: 'bitnami/jasperreports:6.3.0-r11'
    volumes:
-      - 'jasperreports_data:/bitnami'
-      - 'jasperreports_data_v2:/bitnami'
volumes:
-  mariadb_data:
+  mariadb_data_v2:
    driver: local
-  jasperreports_data:
+  jasperreports_data_v2:
    driver: local
```

```
docker-compose up -d
```

4. Wait until it is ready and restore your backup.

```
docker run --network jasperreports_default -t --rm -v $(pwd):/bitnami/backup bitnami/mariadb:10.3 mysql -hmariadb  -ubn_jasperreports -e "source /bitnami/backup/backup.sql" bitnami_jasperreports
```  

Regards.

**Comment by shyamjos** [comment]
Thanks Daniel for the solution, Is there any fix released for this issue or I need to update the image to some other version ?

**Comment by dani8art** [comment]
I would recommend you to update the image to `6.4.3-r30` which is the latest release of the branch `6` for JasperReports application (not major changes). If you choose an older one you could lose the data again.

**Comment by shyamjos** [comment]
I have changed the image tag to `6.4.3-r30` , Now i am unable to select options in server settings page .. (options are not clickable )  , signed in as user user/bitnami

also i am getting this error in docker logs ` log:2020-02-03 12:19:12 26 [Warning] Access denied for user 'bn_jasperreports'@'%' to database 'sugarcrm' `

docker-compose.yaml

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - MARIADB_USER=bn_jasperreports
      - MARIADB_DATABASE=bitnami_jasperreports
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  jasperreports:
    image: 'bitnami/jasperreports:6.4.3-r30'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - JASPERREPORTS_DATABASE_USER=bn_jasperreports
      - JASPERREPORTS_DATABASE_NAME=bitnami_jasperreports
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '3371:8080'
      - '3372:8443'
    volumes:
      - 'jasperreports_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  jasperreports_data:
    driver: local
```

**Comment by dani8art** [comment]
Did you follow all the steps? For me, the update and the database backup work fine. Did you change the name of the volumes as I said? Please, try to follow the steps again.

**Comment by shyamjos** [comment]
Oh I forgot to mention that I am trying set it up from scratch , I have exported the backup file from my previous installation , I planning to restore it to the  version `6.4.3-r30`

**Comment by dani8art** [comment]
Sorry, but I'm not able to reproduce it.

- did you remove your volume? `docker-compose down -v`

- how did you get the backup? if you did it with my steps, I would say you will not able to import it from `Manage` -> `Server Settings` -> `Import`. You must import it from the command line with

```
docker run --network jasperreports_default -t --rm -v $(pwd):/bitnami/backup bitnami/mariadb:10.3 mysql -hmariadb  -ubn_jasperreports -e "source /bitnami/backup/backup.sql" bitnami_jasperreports
```

**Comment by shyamjos** [comment]
Sorry for the delayed response , I talking about the jasper export option (not sql dump)(Manage -> Server Settings -> export) , I already have a export file with me, I am trying to restore it to the jasper version `6.4.3-r30` (fresh install)

but i am not able to click on any menu items in `Manage -> Server Settings` page in  `6.4.3-r30` , Could you please check that ?

**Comment by dani8art** [comment]
Hi @shyamjos 

I did the following step and I can access `Manage -> Server Settings`:

- `docker-compose down -v`
- `docker-compose up -d` 

Regards.
![screenshot](https://user-images.githubusercontent.com/4376304/73827301-94637500-47ff-11ea-9cd1-a1118582a5d9.png)

**Comment by shyamjos** [comment]
It worked fine when I tried it from local machine , But not working in my ec2 instance ?? (not able to select import menu)

**Comment by dani8art** [comment]
Then I would need more information about your ec2 instance, why it is different? it shouldn't be. 

- could you share the os and os version?
- could you share the disk type (EBS, others...)?
- please, share any other relevant information.

Regards.

**Comment by shyamjos** [comment]
I have also noticed that top bar menu items are missing in `Server Settings` Page

![settings page](https://i.imgur.com/2zoMab9.png)

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```
```
uname -a
Linux web-chat-dev 4.15.0-1058-aws #60-Ubuntu SMP Wed Jan 15 22:35:20 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
```
docker -v
Docker version 19.03.5, build 633a0ea838
```

```
docker-compose -v
docker-compose version 1.24.1, build 4667896b
```

```
version: '2'
services:
  mariadb:
    restart: always
    image: 'bitnami/mariadb:10.3'
    environment:
      - MARIADB_USER=bn_jasperreports
      - MARIADB_DATABASE=bitnami_jasperreports
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
    logging:
       driver: syslog

  jasperreports:
    image: 'bitnami/jasperreports:6.4.3-r30'
    restart: always
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - JASPERREPORTS_DATABASE_USER=bn_jasperreports
      - JASPERREPORTS_DATABASE_NAME=bitnami_jasperreports
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '3371:8080'
      - '3372:8443'
    volumes:
      - 'jasperreports_data:/bitnami'
    depends_on:
      - mariadb
    logging:
      driver: syslog
volumes:
  mariadb_data:
    driver: local
  jasperreports_data:
    driver: local
```
