### ISSUE TITLE
Inject a config file in JasperReportServer dock and deploy in Kubernetes

### ISSUE THREAD

**Issue by Tyvain** [bitnami/bitnami-docker-jasperreports#77]
we deploy jasperreport (bitnami image from here: https://hub.docker.com/r/bitnami/jasperreports)

So far so good, everything works well. We made it simple (no volume) for the moment.

The next step is to enable cas login. To do so, We need to copy (inject?) a file  'applicationContext-UNCAuth-CAS.xml' into the WEBINF directory of the tomcat.
The goal is to enable CAS login. 

But we have reading permission error do it, at the start of the dock.

Here is the deploy.yml we have so far:

```
    apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jasper
  name: jasper
  namespace: unc-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jasper
  template:
    metadata:
      labels:
        app: jasper
    spec:
      securityContext:
        runAsUser: 1000
      volumes:
        - name: jasper-config-volume
          configMap:
            name: jasper-config
      containers:
       - image: bitnami/jasperreports:7.2.0
         name: jasper
         env:
           - name: MARIADB_HOST
             value: 127.0.0.1
           - name: MARIADB_PORT_NUMBER
             value: '3306'
           - name: JASPERREPORTS_DATABASE_USER
             value: bn_jasperreports 
           - name: JASPERREPORTS_DATABASE_NAME
             value: bitnami_jasperreports  
           - name: ALLOW_EMPTY_PASSWORD
             value: 'yes'
         volumeMounts:
           - name: jasper-config-volume
             mountPath: /bitnami/tomcat/data/jasperserver/WEB-INF/applicationContext-UNCAuth-CAS.xml
             subPath: applicationContext-UNCAuth-CAS.xml
             readOnly: false
         securityContext:
           runAsUser: 2000
           allowPrivilegeEscalation: false
       - image: bitnami/mariadb:10.3.22
         name: mariadb
         env:
           - name: MARIADB_USER
             value: bn_jasperreports
           - name: MARIADB_PORT_NUMBER
             value: '3306'
           - name: MARIADB_DATABASE
             value: bitnami_jasperreports
           - name: ALLOW_EMPTY_PASSWORD
             value: 'yes'
```
