### ISSUE TITLE
Allow SSL connections to Jasper Reports

### ISSUE THREAD

**Issue by reediculous456** [bitnami/bitnami-docker-jasperreports#79]
## Feature Request

**Description**

I don't see any way to enable SSL connections for jasper through the environment variables, but the docker-compose provided by this repo has port 443 bound to the container.

Can you add SSL support to the container through ENV variables so that I don't need a custom Dockerfile to use SSL?

In order to get SSL working, here are the changes I had to make:

__/bitnami/tomcat/conf/server.xml__

``` xml
...
<Connector port="8443" protocol="org.apache.coyote.http11.Http11AprProtocol"
               maxThreads="150" SSLEnabled="true" >
        <UpgradeProtocol className="org.apache.coyote.http2.Http2Protocol" />
        <SSLHostConfig protocols="TLSv1.1+TLSv1.2">
            <Certificate certificateKeyFile="conf/server.key"
                         certificateFile="conf/server.pem" />
        </SSLHostConfig>
    </Connector>
...
```

__Dockerfile__

``` Dockerfile
RUN apt-get update
RUN apt-get -y install make gcc libssl-dev libapr1-dev

WORKDIR /opt/bitnami/tomcat/bin

RUN tar -xf tomcat-native.tar.gz

WORKDIR tomcat-native-1.2.24-src/native

RUN ./configure && make && make install

RUN printf 'LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CATALINA_HOME/lib\nexport LD_LIBRARY_PATH' > /opt/bitnami/tomcat/bin/setenv.sh

WORKDIR /
```

__docker-compose.yml__
``` yaml
...
jasperreports:
    build: .
    image: jasperreports:7-custom
    container_name: jasperserver
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - JASPERREPORTS_DATABASE_USER=bn_jasperreports
      - JASPERREPORTS_DATABASE_NAME=bitnami_jasperreports
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./server.xml:/bitnami/tomcat/conf/server.xml
      - /etc/certs/server.key:/bitnami/tomcat/conf/server.key
      - /etc/certs/server.cer:/bitnami/tomcat/conf/server.pem
      - jasperreports_data:/bitnami
...
```
