### ISSUE TITLE
Error executing 'postInstallation' on Windows Server 2019 with Linux docker container

### ISSUE THREAD

**Issue by smshafa** [bitnami/bitnami-docker-jasperreports#86]
**Error executing 'postInstallation' on Windows Server 2019 with Linux docker container**

**Steps to reproduce the issue:**

1. Install Linux docker container on Windows Server 2019
2. Use the below docker-compose file:

```
version: '3.4'

services:

    mariadb:
        image: mariadb:latest
        container_name: epms_mariadb
        command: --default-authentication-plugin=mysql_native_password
        environment:
          - MYSQL_ROOT_PASSWORD=example
        ports:
          - 3306:3306
        restart: unless-stopped
        
    jasperreports:
        image: 'docker.io/bitnami/jasperreports:latest'       
        container_name: epms_jasperreports
        environment:
          - MARIADB_HOST=mariadb
          - MARIADB_PORT_NUMBER=3306
          - JASPERREPORTS_DATABASE_USER=jasperreport_user
          - JASPERREPORTS_DATABASE_NAME=bitnami_jasperreports
          - JASPERREPORTS_DATABASE_PASSWORD=example
          - ALLOW_EMPTY_PASSWORD=yes
        ports:
          - '82:8080'
        links:
          - mariadb
        volumes:
          - ./data/jasperreports_data:/bitnami
```

**The results I received:**

Welcome to the Bitnami jasperreports container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-jasperreports
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-jasperreports/issues

nami    INFO  Initializing jasperreports
jasperr INFO  Preparing JasperReports environment...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at mariadb:3306
mysql-c INFO  MySQL server listening and working at mariadb:3306
jasperr INFO  Configuring JasperReports settings...
jasperr INFO  Deploying JasperReports...
Error executing 'postInstallation':      [exec] Result: 128
     [copy] Warning: Could not find file /opt/bitnami/jasperreports/buildomatic/conf_source/templates/keystore-configuration.xml to copy.

BUILD FAILED
/opt/bitnami/jasperreports/buildomatic/bin/import-export.xml:276: The following error occurred while executing this line:
/opt/bitnami/jasperreports/buildomatic/bin/import-export.xml:168: Java returned: 255

Total time: 8 minutes 53 seconds

![image](https://user-images.githubusercontent.com/24754063/103606016-a4616880-4f2a-11eb-9043-b95dbf527f47.png)

In Ubuntu Server, there is no issue and the jasper server works.

**Version**

- Output of `docker version`:

```
Client: Mirantis Container Runtime
 Version:           19.03.14
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        e820475
 Built:             12/17/2020 19:30:16
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Mirantis Container Runtime
 Engine:
  Version:          19.03.14
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       57e3a05525
  Built:            12/17/2020 19:29:00
  OS/Arch:          windows/amd64
  Experimental:     true
```

- Output of `docker info`:

```
Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Mirantis Container Cloud clusters (Mirantis Inc., v1.9.0)

Server:
 Containers: 5
  Running: 1
  Paused: 0
  Stopped: 4
 Images: 15
 Server Version: 19.03.14
 Storage Driver: lcow (linux) windowsfilter (windows)
  LCOW:
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.1637)
 OSType: windows
 Architecture: x86_64
 CPUs: 9
 Total Memory: 10GiB
 Name: EPMS
 ID: 7TEU:73Z4:KNBC:HXKZ:XHEX:D4GH:MJIP:FSWN:6SWP:FURR:P6DG:MRZU
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Username: shafaei
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version`:

```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

Windows Server is installed on the VMware ESXi. 
Ubuntu server is installed on the VMware workstation.

After the MariaDB container is up, I use these command lines to create a database and user:
```
DROP USER IF EXISTS 'jasperreport_user';
CREATE USER 'jasperreport_user'@'%';
CREATE DATABASE IF NOT EXISTS bitnami_jasperreports;
GRANT ALL ON bitnami_jasperreports.* TO 'jasperreport_user'@'%' IDENTIFIED BY 'example';
```
I can see the Jasper tables are created without any data. Also, there is a warning on the MariaDB logs:

epms_mariadb     | 2021-01-04 13:19:43 15 [Warning] Aborted connection 15 to db: 'unconnected' user: 'unauthenticated' host: '172.22.249.133' (This connection closed normally without authentication)
