### ISSUE TITLE
Testing JDBC connection results in security exception

### ISSUE THREAD

**Issue by Walms** [bitnami/bitnami-docker-jasperreports#89]
**Description**

After configuring a JDBC driver to user the MS SQL 2005 driver 
I get the following error when hitting the test button 
"2021-02-03T00:17:38,438 ERROR SecureExceptionHandlerImpl,http-nio-8080-exec-4:116 - There was an error on the server. Try again or contact site administrators. (Error UID: ab194b99-8383-4ec5-bfc9-036db2e69b66)"

**Steps to reproduce the issue:**

1. Add data source resource 
2. Select JDBC
3. Select MS SQL Server driver
4. Add driver 
5. Upload mssql-jdbc-9.2.0.jre8.jar as provided by Microsoft
6. Enter a valid connection string 
7. Hit the test button

Then the loading spinner shows for a while. Then an error will be displayed. 

**Describe the results you received:**

The following in the logs:
2021-02-03T00:17:38,438 ERROR SecureExceptionHandlerImpl,http-nio-8080-exec-4:116 - There was an error on the server. Try again or contact site administrators. (Error UID: ab194b99-8383-4ec5-bfc9-036db2e69b66)
**Describe the results you expected:**
Either success or an error relating to the driver / connection

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**
7-debian-10
- Docker Compose file:

```
version: '3.8'
services:
  salesjaspermariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - MARIADB_USER=bn_jasperreports
      - MARIADB_DATABASE=bitnami_jasperreports
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'sales_jasper_mariadb_data:/bitnami'
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
  salesjasperreports:
    image: 'docker.io/bitnami/jasperreports:7-debian-10'
    environment:
      - MARIADB_HOST=salesjaspermariadb
      - MARIADB_PORT_NUMBER=3306
      - JASPERREPORTS_DATABASE_USER=bn_jasperreports
      - JASPERREPORTS_DATABASE_NAME=bitnami_jasperreports
      - ALLOW_EMPTY_PASSWORD=yes
      - JASPERREPORTS_USERNAME=salesadmin
      - JASPERREPORTS_PASSWORD=REDACTED
      - SMTP_HOST=smtp.sendgrid.net
      - SMTP_PORT=587
      - SMTP_EMAIL=sales_reports@REDACTED
      - SMTP_USER=apikey
      - SMTP_PASSWORD=REDACTED
      - SMTP_PROTOCOL=smtp
    ports:
      - '59866:8080'
    volumes:
      - 'sales_jasperreports_data:/bitnami'
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

    depends_on:
      - salesjaspermariadb
volumes:
  sales_jasper_mariadb_data:
    driver: local
  sales_jasperreports_data:
    driver: local
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Running on docker for windows (Hyper V)
