### ISSUE TITLE
Connection problem with remote DB

### ISSUE THREAD

**Issue by kamrannawaz** [bitnami/bitnami-docker-jasperreports#96]
hi,

i m connecting jasper container to external mysql database which is running in azure app services every time when i run the container i get this logs 
```
Validating settings in MYSQL_CLIENT_* env vars
 Trying to connect to the database server
```
and after some time the container stops, but when i run with another mysql container locally it connects.
how can i resolve the problem. this is my docker-compose file
```
version: '2'
services:
  jasperreports:
    container_name: jasperreports
    image: docker.io/bitnami/jasperreports:7
    environment:
      - JASPERREPORTS_DATABASE_HOST=***
      - JASPERREPORTS_DATABASE_PORT_NUMBER=3306
      - JASPERREPORTS_DATABASE_USER=***
      - JASPERREPORTS_DATABASE_PASSWORD=****
      - JASPERREPORTS_DATABASE_NAME=bitnami_jasperreports
      - MYSQL_CLIENT_DATABASE_HOST=*****
      - MYSQL_CLIENT_DATABASE_PORT_NUMBER=3306
      - MYSQL_CLIENT_DATABASE_ROOT_USER=*****
      - MYSQL_CLIENT_DATABASE_ROOT_PASSWORD=***
      - MYSQL_CLIENT_CREATE_DATABASE_NAME=bitnami_jasperreports
    ports:
      - '8080:8080'
    restart: always
    tty: true
    stdin_open: true

volumes:
  jasperreports_data:
    driver: local
```
