### ISSUE TITLE
Jasper server pod is getting crashed in AKS 

### ISSUE THREAD

**Issue by NagaRajeshK** [bitnami/bitnami-docker-jasperreports#99]
Hi Team,
Could you please help me on this issue?

**Issue**: Jasper pod is getting crashed in one of our environment. It works fine in other environments. We are deploying in AKS latest version 1.20.7. I have redeployed by deleting the volumes as well and tried changing the volume path to "/bitnami/jasperreports" as well but no lock.

**Deployment yaml:**
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jasperreports
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jasperreports
  template:
    metadata:
      labels:
        app: jasperreports
    spec:
     
      containers:
        - name: jasperreports
          image: bitnami/jasperreports:7.8.0
          ports:
            - name: port80
              containerPort: 8080
            - name: port443
              containerPort: 443
          env:  
            - name: MARIADB_HOST
              value: "jasperreportsdbsvc"
            - name: MARIADB_PORT_NUMBER
              value: "3306"
            - name: JASPERREPORTS_DATABASE_USER
              value: "bn_jasperreports"
            - name: JASPERREPORTS_DATABASE_NAME
              value: "bitnami_jasperreports"
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: IMAGE_SERVER_URL
              value: "http://imageflow:3000"
          volumeMounts:
            - mountPath: "/bitnami"
              name: jasperreportfileshare
      volumes:
        - name: jasperreportfileshare
          azureFile:
            secretName: azure-secret-fileshare
            shareName: fs-jasperserver
            readOnly: false
```
**POD LOG:**
```
		[38;5;6mjasperreports [38;5;5m07:32:15.68 [0m
[38;5;6mjasperreports [38;5;5m07:32:15.68 [0m[1mWelcome to the Bitnami jasperreports container[0m
[38;5;6mjasperreports [38;5;5m07:32:15.68 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-jasperreports[0m
[38;5;6mjasperreports [38;5;5m07:32:15.68 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-jasperreports/issues[0m
[38;5;6mjasperreports [38;5;5m07:32:15.69 [0m
[38;5;6mjasperreports [38;5;5m07:32:15.70 [0m[38;5;2mINFO [0m ==> Validating settings in MYSQL_CLIENT_* env vars
[38;5;6mjasperreports [38;5;5m07:32:15.72 [0m[38;5;2mINFO [0m ==> Ensuring Tomcat directories exist
[38;5;6mjasperreports [38;5;5m07:32:15.75 [0m[38;5;2mINFO [0m ==> Configuring port numbers
[38;5;6mjasperreports [38;5;5m07:32:15.78 [0m[38;5;2mINFO [0m ==> Persisted webapps detected
[38;5;6mjasperreports [38;5;5m07:32:15.81 [0m[38;5;3mWARN [0m ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
[38;5;6mjasperreports [38;5;5m07:32:15.93 [0m[38;5;2mINFO [0m ==> Restoring persisted JasperReports installation
**realpath: /bitnami/jasperreports/buildomatic/conf_source/db/mysql/db.template.properties: No such file or directory**  
```
Thanks,
Rajesh.
